### PR TITLE
SeamPay logo

### PR DESCRIPTION
**Pull request by moh-abk**

### CODE REVIEW

**Review by demilad — APPROVED** [review]

**Comment by moh-abk** [comment]
Can we get this merged please 😀

**Review by demilad — CHANGES_REQUESTED** [review]
Hey @moh-abk 
On second review looks like there's some more room for optimisation here.

Ensure your logos have been properly optimised with tools like [SVGOMG](https://jakearchibald.github.io/svgomg/) &
    [Squoosh](https://squoosh.app/)

**Comment by moh-abk** [comment]
SVG processed via `SVGOMG` @demilad

**Comment by demilad** [comment]
Nice @moh-abk, you should run the png through [Squoosh](https://squoosh.app/) as well
The `OxiPNG` setting works well. You can probably reduce the file size by ~50% without a noticeable loss in quality

**Comment by moh-abk** [comment]
PNG processed via Squoosh @demilad

**Review by demilad — APPROVED** [review]

**Review by Odusanya — APPROVED** [review]

**Pull request merged**
