### PR TITLE
category name correction

### PR DESCRIPTION
**Pull request by nimboya**
Correct some category names

### CODE REVIEW

**Comment by fathermerry** [comment]
@nimboya Thanks for this. I'm also considering that "Conglomerate" has been grossly overused now. Can you kindly help take another look and remove "conglomerate" where necessary?

**Comment by fathermerry** [comment]
Hey @nimboya Bubbling this up again

**Comment by nimboya** [comment]
Hello @fathermerry  It is done. Thanks for pointing it out

**Comment by nimboya** [comment]
It pulls the categories from the logos.json file so it will be updated automtically

**Comment by Odusanya** [comment]
Hey @nimboya, any idea why the `FMCG / Conglomerate` and `Ecommerce / Construction / Real Estate` dropdowns don't return any data?

image

-----------------------------------------------------------

image

**Comment by fathermerry** [comment]
> Hey @nimboya, any idea why the `FMCG / Conglomerate` and `Ecommerce / Construction / Real Estate` dropdowns don't return any data?
> 
> image
> 
> image

@nimboya @Odusanya  this is because the category names have changed but have not been corrected in the index.html file.

@nimboya @dbkonxepts worked on better categorization with this PR https://github.com/PaystackHQ/nigerialogos/pull/65 which corrects this issue and some of the categorization issues. I'm going to close this now, but feel free to help the project by taking another look at master to make sure everything is fine.

Thank you so much for contributing.

**Pull request closed without merging**
