### PR TITLE
added logo and company details for thrive agric

### PR DESCRIPTION
**Pull request by Prodigy00**

### CODE REVIEW

**Comment by Prodigy00** [comment]
> Nice @Prodigy00
> Please ensure your logos have been properly optimised with tools like: [SVGOMG](https://jakearchibald.github.io/svgomg/) & [Squoosh](https://squoosh.app/) (OptiPNG works well).

Okay, will do

**Comment by Prodigy00** [comment]
@demilad I've optimized the png and svg logos

**Comment by Prodigy00** [comment]
Hi @demilad I can see that all checks for my PR have been passed but it hasn't been accepted, is there any issue?

**Comment by fathermerry** [comment]
My bad @Prodigy00. Merged now.

**Pull request merged**
