### PR TITLE
Added mono's logo

### PR DESCRIPTION
**Pull request by faarda**

### CODE REVIEW

**Comment by Odusanya** [comment]
Hi Silas @faarda, thanks for your PR. 
Noticed that your PR introduces a yarn-lock file, kindly help take it out.

**Comment by faarda** [comment]
Sorry that was an oversight, file removed

**Comment by demilad** [comment]
Nice @faarda 
Looks like there's some more room for optimisation here.

Ensure your logos have been properly optimised with tools like [SVGOMG](https://jakearchibald.github.io/svgomg/) & [Squoosh](https://squoosh.app/)

**Comment by faarda** [comment]
I've optimized the images further @demilad

**Review by demilad — APPROVED** [review]

**Review by Odusanya — APPROVED** [review]

**Pull request merged**
