### PR TITLE
kadarko martketplace

### PR DESCRIPTION
**Pull request by bosslakrym**
here i have uploaded the logo of kadarko.com marketplace which is an e-commerce marketplace i developed 2017.

I use paystacks as my payment method and also i will be glad to have this featured

### CODE REVIEW

**Comment by fathermerry** [comment]
Hey @bosslakrym, you also need to fill out the JSON entry for your logo in js/logos.json, as described in number 3 here https://github.com/PaystackHQ/nigerialogos/blob/master/contributing.md

**Comment by bosslakrym** [comment]
i have updated the logos.json now

**Comment by bosslakrym** [comment]
i also added a new logo pofela then i added its own logos.json too

**Comment by bosslakrym** [comment]
Is there anything you still expect of me?

Or its all fine?

If it's fine when will it become featured on the website?

**Comment by bosslakrym** [comment]
compressed now using https://jakearchibald.github.io/svgomg/    i have 2
logo folders that i worked on for my brand. kadarko and pofela

pls help me check both

**Comment by bosslakrym** [comment]
all changes done :  PNG's have been optimised with
https://squoosh.app/ preferably
using the OptiPNG option

kadarko and pofela folder

**Pull request merged**
