### PR TITLE
Logo Updates for NIMC and Coat of Arms

### PR DESCRIPTION
**Pull request by MadeByRaymond**
- Updated to be more like what is on the NIMC official website (https://nimc.gov.ng/)
- Other details remain the same
- Included the Nigerian Coat of Arms as a Nigerian Logo

### CODE REVIEW

**Comment by MadeByRaymond** [comment]
@demilad @aeadedoyin

**Review by demilad — CHANGES_REQUESTED** [review]
Nice @MadeByRaymond 

Please remove the Coat of Arms as it is not a Nigerian company

**Comment by MadeByRaymond** [comment]
> Nice @MadeByRaymond
> 
> Please remove the Coat of Arms as it is not a Nigerian company

Done

**Comment by demilad** [comment]
@MadeByRaymond ensure your logos have been optimised using tools like: [SVGOMG](https://jakearchibald.github.io/svgomg/) & [Squoosh](https://squoosh.app/)

**Comment by MadeByRaymond** [comment]
> @MadeByRaymond ensure your logos have been optimised using tools like: [SVGOMG](https://jakearchibald.github.io/svgomg/) & [Squoosh](https://squoosh.app/)

yeah they have

**Comment by MadeByRaymond** [comment]
> @MadeByRaymond ensure your logos have been optimised using tools like: [SVGOMG](https://jakearchibald.github.io/svgomg/) & [Squoosh](https://squoosh.app/)

yeah they have @demilad

**Comment by MadeByRaymond** [comment]
> @MadeByRaymond ensure your logos have been optimised using tools like: [SVGOMG](https://jakearchibald.github.io/svgomg/) & [Squoosh](https://squoosh.app/)

yeah they have @demilad

**Comment by MadeByRaymond** [comment]
@demilad  @aeadedoyin

**Comment by demilad** [comment]
When using [SVGOMG](https://jakearchibald.github.io/svgomg/),  make sure you don't have the `Show original` toggle on when exporting unless you'll end up exporting the original unoptimised version
@MadeByRaymond 
image

**Comment by MadeByRaymond** [comment]
I'd recommend using https://tinypng.com/ or https://tinyjpg.com/ instead. 
It has a better compression and still maintains the quality of the image.

https://squoosh.app/ is good in customizing the prefered settings of the compression.

**Comment by MadeByRaymond** [comment]
The SVG has been compressed using https://jakearchibald.github.io/svgomg/

**Review by Odusanya — APPROVED** [review]

**Review by Odusanya — CHANGES_REQUESTED** [review]

**Review by Odusanya — APPROVED** [review]

**Review by Odusanya — APPROVED** [review]

**Comment by MadeByRaymond** [comment]
Hello @demilad @aeadedoyin, this PR is still pending.

**Review by demilad — APPROVED** [review]

**Comment by MadeByRaymond** [comment]
Still pending

**Comment by MadeByRaymond** [comment]
@demilad @aeadedoyin

**Pull request merged**
