### PR TITLE
Okadabooks logo

### PR DESCRIPTION
**Pull request by itseedris**

### CODE REVIEW

**Comment by itseedris** [comment]
Hi @dbkonxepts I'll review and make a fix.

Thanks.

**Comment by itseedris** [comment]
Hi @dbkonxepts how do I run this on my local? I can't seem to start it.

**Comment by dbkonxepts** [comment]
Seen the updates and adjustments. Cool!
See the [**Readme**](https://github.com/PaystackHQ/nigerialogos/blob/master/README.md) on how to run the project locally.

**Comment by itseedris** [comment]
Thanks, @dbkonxepts got it!

**Pull request merged**
