### PR TITLE
added health_assur_ltd

### PR DESCRIPTION
**Pull request by IDTitanium**

### CODE REVIEW

**Comment by onyekvchi** [comment]
Heyy @IDTitanium , looks like there's an issue with the SVG file you uploaded for this logo:
This is how it shows up:
screen shot 2019-02-13 at 4 29 48 pm

When that's fixed, please run your SVG code through (SVGOMG)[https://jakearchibald.github.io/svgomg/]

Thank you!

**Comment by IDTitanium** [comment]
Yikes! I ll get that fixed. Thanks

**Comment by IDTitanium** [comment]
hi @onyekvchi , please review ...

**Comment by onyekvchi** [comment]
Heyy @IDTitanium, it looks like the new SVG just wraps a PNG file. Is there a change you can get a raw SVG version of the logo instead?

**Comment by IDTitanium** [comment]
hey @onyekvchi I have added a better svg logo... check..

**Pull request merged**
