### PR TITLE
Wallets Africa's new logo

### PR DESCRIPTION
**Pull request by Khanisa**
Hi there!

I am a designer at Wallets Africa. We recently changed from Wallet.ng to Wallets Africa. I just added the new logo and deleted the old.

Thanks.

### CODE REVIEW

**Comment by Khanisa** [comment]
Hi @demilad 

I have deleted the files.

**Comment by Odusanya** [comment]
Hi @Khanisa, sorry if this was probably not communicated explicitly enough.

You were supposed to undo the changes made to `package.json` and `package-lock.json` file and not remove the files entirely from the repo. Please make sure the versions of package.json and package-lock.json match the files in the master branch.

**Comment by Khanisa** [comment]
@demilad so sorry. I just restored the file and deleted the changes.

**Comment by fathermerry** [comment]
Heey @demilad @Khanisa Is there any reason why we're moving the package.json and package-lock files into the js folder?

**Comment by fathermerry** [comment]
@Khanisa Hey. I think we got the PR in from the Airtable form and we've added the logo now. I'm going to close this PR, thanks.

**Pull request closed without merging**
