### PR TITLE
All company urls linked to the official website (if valid) or Google search (if empty or invalid)

### PR DESCRIPTION
**Pull request by tonyfrenzy**
- No disruption of design, UI or UX.

### CODE REVIEW

**Comment by tonyfrenzy** [comment]
nigerialogos_update

- A preview of the addition.
- All urls open in a new tab.

**Comment by aeadedoyin** [comment]
This is dope. 🔥🔥🔥
However, the link(both the official site and google search) seems to disappear upon search.

**Comment by tonyfrenzy** [comment]
> This is dope. 🔥🔥🔥
> However, the link(both the official site and google search) seems to disappear upon search.

Oh, I didn't check that.
WIll visit that on my next free time or if anyone can provide the fix sooner though.

**Comment by tonyfrenzy** [comment]
@aeadedoyin link disappearance in search now fixed!

**Pull request merged**
