### PR TITLE
Add Techpoint Africa logo

### PR DESCRIPTION
**Pull request by ize-302**

### CODE REVIEW

**Review by demilad — CHANGES_REQUESTED** [review]
Nice @ize-302 
Looks like there's a little more room for optimisation on the Techpoint SVG. 
You can use [SVGOMG](https://jakearchibald.github.io/svgomg/) for that

**Comment by ize-302** [comment]
> Nice @ize-302 Looks like there's a little more room for optimisation on the Techpoint SVG. You can use [SVGOMG](https://jakearchibald.github.io/svgomg/) for that

Optimized the image already using the same SVGOMG, was quite surprised there was very little difference in filesize.

**Comment by demilad** [comment]
@ize-302 ensure you don't have `Show original` enabled when exporting the optimised version.
It should look like this 
image

**Comment by ize-302** [comment]
> @ize-302 ensure you don't have `Show original` enabled when exporting the optimised version. It should look like this image

Thanks, that was helpful. The file size is reduced by about 3kb

**Review by demilad — APPROVED** [review]

**Pull request merged**
