### PR TITLE
BigiBrand logo

### PR DESCRIPTION
**Pull request by thealaoifeoluwa**
BigiBrand Logo

### CODE REVIEW

**Review by demilad — CHANGES_REQUESTED** [review]
Nice @thealaoifeoluwa 

Looks like there's some more room for optimisation here. Please ensure your logo files have been optimised using tools like: [SVGOMG](https://jakearchibald.github.io/svgomg/) & [Squoosh](https://squoosh.app/)

**Comment by thealaoifeoluwa** [comment]
Have optimized the file, but I realized the SVG file size is not reducing

**Review by thealaoifeoluwa — COMMENTED** [review]
I have optimized the files but realized the SVG file is not reducing after optimization.

**Review by thealaoifeoluwa — COMMENTED** [review]
I have optimized the files but realized the SVG file is not reducing after optimization.

**Comment by demilad** [comment]
When using [SVGOMG](https://jakearchibald.github.io/svgomg/),  make sure you don't have the `Show original` toggle on when exporting unless you'll end up exporting the original unoptimised version
@thealaoifeoluwa 
image

**Comment by thealaoifeoluwa** [comment]
all right

**Review by demilad — APPROVED** [review]

**Comment by thealaoifeoluwa** [comment]
@demilad   Please when is this going to be merged?

**Pull request merged**
