### PR TITLE
Fundall Logo Upload

### PR DESCRIPTION
**Pull request by wumzee97**

### CODE REVIEW

**Review by demilad — CHANGES_REQUESTED** [review]
Hey @wumzee97 thanks for your contribution.
I noticed your SVG logo is actually a png wrapped as an SVG. To ensure high quality logos, we only accept pure vector SVG's that are infinitely scaleable without losing quality.
I'll suggest you either reach out to the logo designer for the original vector files or recreate the logo from scratch in a vector tool l like Inkscape or Illustrator (requires more effort as you have to make a pixel perfect recreation for your contribution to be added)

**Comment by wumzee97** [comment]
Thanks, Demilade.

I have forwarded your response/requirements to our creative designer and we
are currently working on it.

Once done, I will update and initiate another pull request.

Thanks once again.

**Comment by demilad** [comment]
@wumzee97 no need to make a new pull request. You can just update the file and push as a new commit to this PR

**Comment by wumzee97** [comment]
Will do, thanks!

**Comment by wumzee97** [comment]
Hi Demilade,

I have updated the SVG logo, I've also pushed. Kindly check and do let me
know if there are other issues.

Thanks.

**Review by demilad — APPROVED** [review]

**Comment by wumzee97** [comment]
Awesome, thanks!

**Comment by wumzee97** [comment]
Hi Demilade,

Please the Fundall logo isn't reflecting on https://nigerialogos.com/ yet.

Thanks for your further action on this.

**Comment by demilad** [comment]
@Odusanya please help merge

**Comment by wumzee97** [comment]
Awesome, thanks!

**Pull request merged**
